# -*- coding: utf-8 -*-
"""Análise-Exploratóra-de-Dados-2504

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yauSkJOFFUkaB1aHDEWnTcsjmZ-mKKOu
"""

import numpy as np
import pandas as pd

dadosDeputados = pd.read_csv('cota-parlamentar.csv')

dadosDeputados.columns

dadosDeputados = dadosDeputados.drop(columns=['codlegislatura', 'idedocumento',
                                              'idecadastro', 'indtipodocumento',
                                              'nucarteiraparlamentar', 'nulegislatura',
                                              'numespecificacaosubcota', 'numlote',
                                              'nummes', 'numparcela', 'numressarcimento',
                                              'numsubcota', 'txtcnpjcpf', 'txtdescricao',
                                              'txtfornecedor', 'txtnumero', 'txtpassageiro',
                                              'txttrecho', 'vlrglosa', 'vlrrestituicao'])

dadosDeputados.head()

"""#### Verificando o Tipo de Dado"""

dadosDeputados['datemissao'].unique()

dadosDeputados['nudeputadoid'].unique()

dadosDeputados['numano'].unique()

dadosDeputados['sgpartido'].unique()

dadosDeputados['txnomeparlamentar'].unique()

dadosDeputados['txtdescricaoespecificacao'].unique()

dadosDeputados['vlrdocumento'].unique()

dadosDeputados['vlrliquido'].unique()

dadosDeputados['datemissao']

"""#### Tratamento dos Dados"""

def tratamentoData(x):
  try:
    dia = str(x)[8:10]
    mes = str(x)[5:7]
    ano = str(x)[:4]
    return dia+'/'+mes+'/'+ano
  except:
    pass

dataFrameData = dadosDeputados['datemissao']
dataFrameData = pd.DataFrame(dataFrameData)

dataFrameData = dataFrameData.applymap(tratamentoData)

dadosDeputados['vlrdocumento'] = dadosDeputados['vlrdocumento'].astype(float)

dadosDeputados.drop(columns=['vlrliquido'])

dadosDeputados['datemissaoNova'] = dataFrameData['datemissao']

dadosDeputados.head()

"""#### Casos Atípicos"""

print(dadosDeputados['vlrdocumento'].min())
print(dadosDeputados['vlrdocumento'].max())
print(dadosDeputados['vlrdocumento'].mean())

dadosDeputados = dadosDeputados[(dadosDeputados['vlrdocumento'] > 0)].reset_index(drop=True)

dadosDeputados = dadosDeputados[(
    ~dadosDeputados['txnomeparlamentar'].str.contains('LIDERANÇA'))].reset_index(drop=(True))

dadosDeputados['txnomeparlamentar'].unique()

dadosDeputados = dadosDeputados[(dadosDeputados['sgpartido'] !=
                                 dadosDeputados['txnomeparlamentar'])].reset_index(drop=True)

"""#### Dados Ausentes"""

dadosDeputados = dadosDeputados.dropna(subset=['datemissao']).reset_index(drop=True)

dadosDeputados[(dadosDeputados['nudeputadoid'].isnull() == True)]

def tratamentoTexto(x):
  try:
    teste = x[0]
    return x
  except:
    return "Não Informado"

dataFrameTexto = dadosDeputados['txtdescricaoespecificacao']
dataFrameTexto = pd.DataFrame(dataFrameTexto)

dataFrameTexto = dataFrameTexto.applymap(tratamentoTexto)

dadosDeputados['txtdescricaoespecificacao'] = dataFrameTexto['txtdescricaoespecificacao']

dadosDeputados['txtdescricaoespecificacao'].unique()

"""#### Gráficos"""

listaAnos = dadosDeputados['numano'].unique()
listaAnos

listaValores = list()
for i in range(len(listaAnos)):
  listaValores.append(
      dadosDeputados[(dadosDeputados['numano'] == listaAnos[i])]['vlrdocumento'].sum()
  )

import matplotlib.pyplot as plt

plt.figure(figsize=(10,7))
plt.bar(listaAnos, listaValores)
plt.xticks(listaAnos)
plt.ylabel('Valores')
plt.xlabel('Anos')
plt.title('Valores por Ano')
plt.show()

"""#### Gráfico de Pizza"""

listaPartidos = dadosDeputados['sgpartido'].unique()

listaValoresNovo = list()

for i in range(len(listaPartidos)):
  listaValoresNovo.append(
      dadosDeputados[(dadosDeputados['sgpartido'] == listaPartidos[i])]['vlrdocumento'].sum()
  )

fig1, ax1 = plt.subplots()
ax1.pie(listaValoresNovo, labels=listaPartidos)
ax1.axis('equal')
plt.show()

"""#### Análise RFM"""

dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '9009-11-03 00:00:00'].index, 'datemissao']  = '2009-11-03 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '8201-08-27 00:00:00'].index, 'datemissao']   = '2012-08-27 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '5201-05-03 00:00:00'].index, 'datemissao']   = '2010-05-03 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '5020-10-23 00:00:00'].index, 'datemissao']  = '2010-10-23 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '5012-06-28 00:00:00'].index, 'datemissao']  = '2012-06-28 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '5011-05-30 00:00:00'].index, 'datemissao']   = '2011-05-30 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '5010-04-26 00:00:00'].index, 'datemissao']   = '2010-04-26 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '3012-10-31 00:00:00'].index, 'datemissao']   = '2012-10-31 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '3012-04-16 00:00:00'].index, 'datemissao']   = '2012-04-16 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2301-01-10 00:00:00'].index, 'datemissao']   = '2012-01-10 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-12-17 00:00:00'].index, 'datemissao']   = '2009-12-17 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-12-09 00:00:00'].index, 'datemissao']   = '2009-12-09 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-11-23 00:00:00'].index, 'datemissao']   = '2009-11-23 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-11-19 00:00:00'].index, 'datemissao']   = '2009-11-19 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-10-22 00:00:00'].index, 'datemissao']  = '2009-10-22 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-10-13 00:00:00'].index, 'datemissao']   = '2009-10-13 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-10-05 00:00:00'].index, 'datemissao']   = '2009-10-05 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-10-01 00:00:00'].index, 'datemissao']   = '2009-10-01 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-09-21 00:00:00'].index, 'datemissao']   = '2009-09-21 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-09-07 00:00:00'].index, 'datemissao']   = '2009-09-07 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-09-02 00:00:00'].index, 'datemissao']   = '2009-09-02 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-08-27 00:00:00'].index, 'datemissao']   = '2009-08-27 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-08-20 00:00:00'].index, 'datemissao']   = '2009-08-20 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2209-08-07 00:00:00'].index, 'datemissao']   = '2009-08-07 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2201-02-07 00:00:00'].index, 'datemissao']   = '2012-02-07 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2201-01-07 00:00:00'].index, 'datemissao']  = '2010-01-07 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2200-07-22 00:00:00'].index, 'datemissao']   = '2009-07-22 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2111-10-05 00:00:00'].index, 'datemissao']   = '2011-10-05 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2111-01-31 00:00:00'].index, 'datemissao']   = '2011-01-31 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2100-09-04 00:00:00'].index, 'datemissao']   = '2009-09-04 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2099-11-30 00:00:00'].index, 'datemissao']   = '2009-11-30 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2099-11-18 00:00:00'].index, 'datemissao']   = '2009-11-18 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2099-11-16 00:00:00'].index, 'datemissao']   = '2009-11-16 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2099-07-09 00:00:00'].index, 'datemissao']   = '2009-07-09 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2099-06-02 00:00:00'].index, 'datemissao']  = '2009-06-02 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2090-11-28 00:00:00'].index, 'datemissao']   = '2009-11-28 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2077-06-30 00:00:00'].index, 'datemissao']   = '2011-06-30 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2042-04-02 00:00:00'].index, 'datemissao']   = '2012-04-02 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2021-08-03 00:00:00'].index, 'datemissao']   = '2010-08-03 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2020-10-24 00:00:00'].index, 'datemissao']   = '2010-10-24 00:00:00'
dadosDeputados.loc[dadosDeputados[dadosDeputados['datemissao'] == '2020-10-08 00:00:00'].index, 'datemissao']   = '2010-10-08 00:00:00'

from datetime import date

dadosRFM = pd.DataFrame()

dadosRFM['txnomeparlamentar'] = dadosDeputados['txnomeparlamentar'].unique()

dadosRFM

"""#### Quantidade de Dias"""

dadosRFM['diasUltimaCompra'] = ''
maxima = pd.to_datetime('2020-12-31')

for i in range(len(dadosRFM)):
  data = pd.to_datetime(dadosDeputados[dadosDeputados['txnomeparlamentar'] == dadosRFM['txnomeparlamentar'][i]['datemissao'].max())]
  diff = maxima - data
  dadosRFM.loc[i, 'diasUltimaCompra'] = diff.days

